### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Akiramex** [jark006/SummerTTS_VS#1]
\eigen-3.4.0\Eigen\Dense(1,10): fatal  error C1083: 无法打开包括文件: “Core”: No such file or directory

**Comment by jark006** [comment]
> \eigen-3.4.0\Eigen\Dense(1,10): fatal error C1083: 无法打开包括文件: “Core”: No such file or directory

我把Include目录写成绝对目录了，现在改为相对目录了，你现在同步最新代码再试试

**Comment by Akiramex** [comment]
依然报同样的错误，路径找不到Core文件

**Comment by jark006** [comment]
> 依然报同样的错误，路径找不到Core文件

你检查一下项目属性>VC++目录>包含目录，是否含有以下：
```
$(ProjectDir)eigen-3.4.0
$(ProjectDir)src\tn\header
$(ProjectDir)include
$(ProjectDir)src\header
```
再重新生成解决方案

**Comment by Akiramex** [comment]
我确认\eigen-3.4.0\Eigen\里面没有Core文件，我从原项目复制过来重新生成解决方案，发生以下错误：
错误	MSB6006	“link.exe”已退出，代码为 -1073740791。	SummerTTS_VS	C:\0_Akira\0_Work\0_Program\Microsoft Visual Studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	1096

**Comment by jark006** [comment]
> 我确认\eigen-3.4.0\Eigen\里面没有Core文件，我从原项目复制过来重新生成解决方案，发生以下错误： 错误 MSB6006 “link.exe”已退出，代码为 -1073740791。 SummerTTS_VS C:\0_Akira\0_Work\0_Program\Microsoft Visual Studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets 1096

感觉这次应该行了，你再试试同步代码。问题源于 `eigen-3.4.0` 目录里的 `.gitignore` 文件里排除了“core”之类的文件，导致项目再传到github时，漏了一堆文件，但这个目录所有内容都是clone自原作者的，没有任何改动，不知道原仓库还是eigen库出了什么问题
