### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by nanfei01055** [jark006/SummerTTS_VS#2]
这个版本的在 windows 下运行时有内存泄漏问题，当程序关闭时，也就是对象析构时报错，有时也会在运行时崩溃，VS直接提示的是“SynthesizerTrn” 在析构时报错，但调试时代码精确报错位置无法确定，原作者的程序在安卓下很稳定，这个项目有一些改动，我没找到是哪里出问题了，希望作者可以修复这个问题

**Comment by jark006** [comment]
> 这个版本的在 windows 下运行时有内存泄漏问题，当程序关闭时，也就是对象析构时报错，有时也会在运行时崩溃，VS直接提示的是“SynthesizerTrn” 在析构时报错，但调试时代码精确报错位置无法确定，原作者的程序在安卓下很稳定，这个项目有一些改动，我没找到是哪里出问题了，希望作者可以修复这个问题

这bug有没有稳定复现的步骤或数据样本

**Comment by nanfei01055** [comment]
用以下代码，可以生成输出语音，但无法输出 “over”，因为程序在销毁 synthesizer 时崩溃了：
```
#include <iostream>
#include <fstream>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <fcntl.h>

#include "SynthesizerTrn.h"
#include "utils.h"

using std::cout;
using std::cerr;
using std::endl;
using std::vector;

void convertAudioToWavBuf(
    char* toBuf,
    char* fromBuf,
    int totalAudioLen)
{
    char* header = toBuf;
    int byteRate = 16 * 16000 * 1 / 8;
    int totalDataLen = totalAudioLen + 36;
    int channels = 1;
    int  longSampleRate = 16000;

    header[0] = 'R'; // RIFF/WAVE header
    header[1] = 'I';
    header[2] = 'F';
    header[3] = 'F';
    header[4] = (char)(totalDataLen & 0xff);
    header[5] = (char)((totalDataLen >> 8) & 0xff);
    header[6] = (char)((totalDataLen >> 16) & 0xff);
    header[7] = (char)((totalDataLen >> 24) & 0xff);
    header[8] = 'W';
    header[9] = 'A';
    header[10] = 'V';
    header[11] = 'E';
    header[12] = 'f'; // 'fmt ' chunk
    header[13] = 'm';
    header[14] = 't';
    header[15] = ' ';
    header[16] = 16; // 4 bytes: size of 'fmt ' chunk
    header[17] = 0;
    header[18] = 0;
    header[19] = 0;
    header[20] = 1; // format = 1
    header[21] = 0;
    header[22] = (char)channels;
    header[23] = 0;
    header[24] = (char)(longSampleRate & 0xff);
    header[25] = (char)((longSampleRate >> 8) & 0xff);
    header[26] = (char)((longSampleRate >> 16) & 0xff);
    header[27] = (char)((longSampleRate >> 24) & 0xff);
    header[28] = (char)(byteRate & 0xff);
    header[29] = (char)((byteRate >> 8) & 0xff);
    header[30] = (char)((byteRate >> 16) & 0xff);
    header[31] = (char)((byteRate >> 24) & 0xff);
    header[32] = (char)(1 * 16 / 8); // block align
    header[33] = 0;
    header[34] = 16; // bits per sample
    header[35] = 0;
    header[36] = 'd';
    header[37] = 'a';
    header[38] = 't';
    header[39] = 'a';
    header[40] = (char)(totalAudioLen & 0xff);
    header[41] = (char)((totalAudioLen >> 8) & 0xff);
    header[42] = (char)((totalAudioLen >> 16) & 0xff);
    header[43] = (char)((totalAudioLen >> 24) & 0xff);

    memcpy(toBuf + 44, fromBuf, totalAudioLen);

}


int main(int argc, char** argv) {
    
    float* dataW = NULL;
    int32_t modelSize = ttsLoadModel((char*)"d:\\single_speaker_fast.bin", &dataW);

    SynthesizerTrn* synthesizer = new SynthesizerTrn(dataW, modelSize);

    int32_t spkNum = synthesizer->getSpeakerNum();

    int32_t retLen = 0;
    int16_t* wavData = synthesizer->infer("你听到我的声音了吗", 0, 1.0, retLen);

    char* dataForFile = new char[retLen * sizeof(int16_t) + 44];
    convertAudioToWavBuf(dataForFile, (char*)wavData, retLen * sizeof(int16_t));

    FILE* fpOut = fopen("d:\\out.wav", "wb");
    fwrite(dataForFile, retLen * sizeof(int16_t) + 44, 1, fpOut);
    fclose(fpOut);
    tts_free_data(wavData);

    delete synthesizer;
    tts_free_data(dataW);

    cout << "over" << endl;


    return 0;
}
```

**Comment by jark006** [comment]
修好了，同步一下最新代码即可，详情：https://github.com/jark006/SummerTTS_VS/commit/7d02ddad8fac8b8d1322d9af3e41b3ad9e14dcf0
原因是用错了小括号来new数组：
`xxx = new int_t(xxx);//wrong`
`xxx = new int_t[xxx];//right`

**Comment by nanfei01055** [comment]
感谢你修复了崩溃的问题，而且 Debug 模式也得到了修复，可以调试程序了

**Comment by nanfei01055** [comment]
但似乎并没有完全修复内存泄漏的问题，我用以下代码做了测试，每进行一个循环，在任务管理器里观察，内存会上升 > 0.5M，如果这个也能修复，就可以创建多个对象进行并行朗读了，虽然这个场景对现阶段的我来说并不太重要，这是我的测试：

`int main(int argc, char** argv) {

    for (int i = 0; i < 1000000; i++)
    {
        cout << "press any key to continue..." << endl;
        (void)getchar();
        cout << i << endl;

        float* dataW = NULL;
        int32_t modelSize = ttsLoadModel((char*)"d:\\single_speaker_fast.bin", &dataW);

        SynthesizerTrn* synthesizer = new SynthesizerTrn(dataW, modelSize);
        int32_t spkNum = synthesizer->getSpeakerNum();

        int32_t retLen = 0;
        int16_t* wavData = synthesizer->infer("你听到我的声音了吗", 0, 1.0, retLen);

        char* dataForFile = new char[retLen * sizeof(int16_t) + 44];
        convertAudioToWavBuf(dataForFile, (char*)wavData, retLen * sizeof(int16_t));

        PlaySound((LPCSTR)dataForFile, 0, SND_MEMORY | SND_SYNC);

        FILE* fpOut = fopen("d:\\out.wav", "wb");
        fwrite(dataForFile, retLen * sizeof(int16_t) + 44, 1, fpOut);
        fclose(fpOut);

        delete[] dataForFile;  // 释放 dataForFile 对象
        tts_free_data(wavData);  // 释放 wavData 对象
        delete synthesizer;  // 释放 synthesizer 对象
        tts_free_data(dataW);  // 释放 dataW 对象
    }

    cout << "over" << endl;

    return 0;
}`

**Comment by jark006** [comment]
> 但似乎并没有完全修复内存泄漏的问题，我用以下代码做了测试，每进行一个循环，在任务管理器里观察，内存会上升 > 0.5M，如果这个也能修复，就可以创建多个对象进行并行朗读了，虽然这个场景对现阶段的我来说并不太重要，这是我的测试：
> 
> ```
> int main(int argc, char** argv) {
> for (int i = 0; i < 1000000; i++)
> {
>     cout << "press any key to continue..." << endl;
>     (void)getchar();
>     cout << i << endl;
> 
>     float* dataW = NULL;
>     int32_t modelSize = ttsLoadModel((char*)"d:\\single_speaker_fast.bin", &dataW);
> 
>     SynthesizerTrn* synthesizer = new SynthesizerTrn(dataW, modelSize);
>     int32_t spkNum = synthesizer->getSpeakerNum();
> 
>     int32_t retLen = 0;
>     int16_t* wavData = synthesizer->infer("你听到我的声音了吗", 0, 1.0, retLen);
> 
>     char* dataForFile = new char[retLen * sizeof(int16_t) + 44];
>     convertAudioToWavBuf(dataForFile, (char*)wavData, retLen * sizeof(int16_t));
> 
>     PlaySound((LPCSTR)dataForFile, 0, SND_MEMORY | SND_SYNC);
> 
>     FILE* fpOut = fopen("d:\\out.wav", "wb");
>     fwrite(dataForFile, retLen * sizeof(int16_t) + 44, 1, fpOut);
>     fclose(fpOut);
> 
>     delete[] dataForFile;  // 释放 dataForFile 对象
>     tts_free_data(wavData);  // 释放 wavData 对象
>     delete synthesizer;  // 释放 synthesizer 对象
>     tts_free_data(dataW);  // 释放 dataW 对象
> }
> 
> cout << "over" << endl;
> 
> return 0;
> }
> ```

我使用以下代码测试了一下，Release模式听到了50次，Debug模式听到了40次，进程的内存占用一直在22MB小波动，并没有内存泄漏现象。cppCheck也简单检查了一下，在`src\tn\header\fst\disambiguate.h` #380行发现nopts.filter可能有问题，但没法确认它有没有在 #397、#401 `DeterminizeFst<Arc>(ifst, nopts)` 被转移或释放。

```

int main() {
    for (int i = 0; i < 1000000; i++){
        float* dataW = NULL;
        int32_t modelSize = ttsLoadModel((char*)"D:\\SummerTTSModels\\single_speaker_fast.bin", &dataW);

        SynthesizerTrn* synthesizer = new SynthesizerTrn(dataW, modelSize);
        int32_t spkNum = synthesizer->getSpeakerNum();

        string str = "第" + std::to_string(i) + "次，你听到我的声音了吗";
        int32_t retLen = 0;
        int16_t* wavData = synthesizer->infer(str.c_str(), 0, 1.0, retLen);
        cout << str << endl;

        char* dataForFile = new char[retLen * sizeof(int16_t) + 44];
        convertAudioToWavBuf(dataForFile, (char*)wavData, retLen * sizeof(int16_t));

        PlaySound((LPCSTR)dataForFile, 0, SND_MEMORY | SND_SYNC);

        FILE* fpOut = fopen("d:\\out.wav", "wb");
        fwrite(dataForFile, retLen * sizeof(int16_t) + 44, 1, fpOut);
        fclose(fpOut);

        delete[] dataForFile;  // 释放 dataForFile 对象
        tts_free_data(wavData);  // 释放 wavData 对象
        delete synthesizer;  // 释放 synthesizer 对象
        tts_free_data(dataW);  // 释放 dataW 对象
    }

    cout << "over" << endl;

    return 0;
}
```

**Comment by nanfei01055** [comment]
好的，非常感谢

**Comment by jark006** [comment]
> 好的，非常感谢

你要是真的有内存泄漏，那就搞成全局生命周期吧，进程退出前都不要析构了，反正一个对象实例也就20MB左右，也不会用太多内存
